name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add wasm32-unknown-unknown
      - run: wget https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.83/wasm-bindgen-0.2.83-x86_64-unknown-linux-musl.tar.gz
      - run: tar -xzf wasm-bindgen-0.2.83-x86_64-unknown-linux-musl.tar.gz
      - run: mv wasm-bindgen-0.2.83-x86_64-unknown-linux-musl/wasm-bindgen ~/.cargo/bin
      - run: yarn
      - run: npx prettier --check .
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
