name: Release
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --package minkowski --token ${{ secrets.CARGO_TOKEN }}
